name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: pwd ; ls -lart ; ls -lart .. ; ls -lart ../.. ; ./build.sh
