name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      -
        name: Check out repository code
        uses: actions/checkout@v3
      -
        run: ./build.sh
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          #push: true
          #tags: ${{ secrets.DOCKER_HUB_USERNAME }}/clockbox:latest
          #tags: ${{ secrets.DOCKER_HUB_USERNAME }}/diy-accounting-zips:latest
          tags: diy-accounting-zips:latest
      -
        run: docker images ls
